name: Project-Flow

on:
  push:
    branches:
      - main
    paths:
      - 'project/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r project/requirements.txt

      - name: Debug
        run: 
          ls -la $HOME/.kaggle
          cat $HOME/.kaggle/kaggle.json

      - name: Install Kaggle API
        run: 
          pip install kaggle
          mkdir -p $HOME/.kaggle
          echo "$KAGGLE_TOKEN" > $HOME/.kaggle/kaggle.json
          chmod 600 $HOME/.kaggle/kaggle.json
          export KAGGLE_CONFIG_DIR=$HOME/.kaggle


      - name: Run pipline.py
        run: python project/pipeline.py
        
      - name: Run test.py
        run: python project/test.py